### ISSUE TITLE
Keypresses getting propagated from a launched program to Cesium when exiting

### ISSUE THREAD

**Issue by andressevilla** [MateoConLechuga/Cesium#1] opened 2015-10-13 23:13 UTC
Will capture last key press when closing programs

Ex:Open calcuzap,press clear, cesium will close.

**Comment by Eeems** [comment] 2015-10-13 23:16
Can confirm that this happens in calcuzap. It must be something to do with how calcuzap handles the keypresses though, other programs don't cause cesium to close when pressing clear to exit.

**Comment by adriweb** [comment] 2015-10-13 23:32
Might there be a way to clear the "key buffer" as soon as Cesium regains control, though?

**Comment by Eeems** [comment] 2015-10-13 23:42
Looks like getkey is part of the main loop https://github.com/MateoConLechuga/Cesium/blob/master/src/routines/main.asm#L57
Waiting for all keys to be released before going back to the main loop might be a good idea. From what I can tell, it already is here https://github.com/MateoConLechuga/Cesium/blob/5bfb9bdd93aaf923492b4cef4d3cb371849acb6d/src/routines/common.asm#L38
It might be good to poke Patrick about how calcuzap exits to see if he's doing something strange.

**Comment by adriweb** [comment] 2015-10-13 23:52
I have a fix: `di` before ` call DeletePgrmFromUserMem` and `ei` before ` jp RELOADED_FROM_PRGM`.
Confirmed to work with Calculzap.
Looks good?

**Comment by MateoConLechuga** [comment] 2015-10-13 23:54
Um. If you enable interrupts, that means TIOS interrupts will be executing.
If it works, sure.

**Comment by adriweb** [comment] 2015-10-13 23:55
Hmm.
Well, I have pinged PatrickD on IRC, so we'll see what he thinks about his keypress handling related to that issue.

**Comment by Eeems** [comment] 2015-10-13 23:58
You might want to just `di`. For all we know calcuzap enables interrupts Cesium wasn't handling them being on again properly.

**Comment by adriweb** [comment] 2015-10-13 23:59
Yeah that looks safe enough.
I'll try that and commit soon.

**Comment by adriweb** [comment] 2015-10-14 00:59
Actually, not doing `ei` doesn't fix the behaviour. Only  `di` \ ... \ `ei` fixes it. I guess we'll have to go with that.

**Comment by adriweb** [comment] 2015-10-14 01:26
Fixed in 1.1.2 (commit: https://github.com/MateoConLechuga/Cesium/commit/305c7ff172d7b879cce28cbf93ddbf336c731209)
Go redownload the binaries (8xp files) and give it a try.

Closing the issue for now.

**Closed by adriweb** 2015-10-14 01:26 UTC

**Comment by Eeems** [comment] 2015-10-15 00:49
I've just tested and can confirm that this is fixed.
