### ISSUE TITLE
USB Drive Support Not Working

### ISSUE THREAD

**Issue by KnightsWhoSayNi0** [mateoconlechuga/cesium#166] opened 2021-03-01 04:12 UTC
## Calc Info
Model: TI-84 Plus CE
OS: 5.4.0.0034
PROD #: 13-07-05-2200
ID: 13005-7D113
Boot Code: 5.1.5.0014
Base Code: 5.4.0.0034

## Other Info
USB Drive: Verbatim STORE N GO USB Device (14.4 GB)
Formatted in FAT32 with windows 10 (yes i know pleb move, but i have to use windows for school :( )
I put a build of MULE CE on it. (45 KB program)

OTG Cable: Unlabeled, but seems to be [this one](https://www.ebay.com/itm/Mini-Short-5-pin-Male-to-USB-2-0-Type-A-Female-Jack-OTG-Host-Adapter-Cable-F2/402600600682?_trkparms=aid%3D1110009%26algo%3DSPLICE.COMPLISTINGS%26ao%3D1%26asc%3D231170%26meid%3D97ce8da11cf542c1bc7bf71b84498890%26pid%3D101196%26rk%3D2%26rkt%3D12%26mehot%3Dpf%26sd%3D252317463073%26itm%3D402600600682%26pmt%3D1%26noa%3D0%26pg%3D2047675%26algv%3DItemStripV101HighAdFee%26brand%3DUnbranded&_trksid=p2047675.c101196.m2219)

## Reproduction Steps
1. Turn on calculator
2. Apps, 4, to enter Cesium
3. Click on USB Flash Drive in Cesium
4. Plug drive into OTG cable
5. Plug Cable into calculator
6. Nothing Happens
7. Unplug cable
8. Press CLEAR
9. Try the USB cable first, then the drive
10. Nothing happens
11. Remove the cable
12. Calculator is frozen. CLEAR does nothing, neither does any other button.

Once hung, no combination of anything will unfreeze the calculator.

Please let me know of any errors in this bug report.
Thanks! -Knights

**Comment by mateoconlechuga** [comment] 2021-03-01 05:08
Thanks for the report! What is the date code/model number on the back of the calculator?

**Comment by KnightsWhoSayNi0** [comment] 2021-03-01 05:20
Woops forgot about that!

## Formatting Settings
Capacity: 14.4 GB
File System: FAT32
Allocation Unit Size: 16 kilobytes

## More calc things because im dumb
Code: L-0318L

**Comment by mateoconlechuga** [comment] 2021-03-01 05:28
As a pro-tip, you should set the allocation unit size to 64KiB for best performance. Anyway I'll get those materials and see if I can reproduce it.

**Comment by KnightsWhoSayNi0** [comment] 2021-03-01 05:50
It was the drive.
Tried it with a different drive and it works perfectly.

**Comment by mateoconlechuga** [comment] 2021-03-01 05:57
Well probably not "perfectly" as there might be intermittent issues. I'm going to keep this topic open because I was able to reproduce this issue on another drive I have, so until I fix that I'll be working on making this more stable.

**Comment by KnightsWhoSayNi0** [comment] 2021-03-01 06:00
I personally think the issue is just the cheap usb drive, but there definitely are some problems so this should be kept open.

**Comment by Marasme** [comment] 2021-10-14 05:37
Thanks

**Comment by mateoconlechuga** [comment] 2021-10-14 05:48
I'm going to close this issue for now, unless @KnightsWhoSayNi0 wants to test that other drive again. I think that the usb libraries are able to better handle various drives now, so most drives should work.

**Closed by mateoconlechuga** 2021-10-14 05:48 UTC
Labels: bug
