### ISSUE TITLE
ClrHome not Clearing

### ISSUE THREAD

**Issue by LogicalJoe** [mateoconlechuga/cesium#87] opened 2019-03-16 19:56 UTC
ClrHome sometimes does not clear the home, the best example of this I can provide is:
`Input A:ClrHome:Input B`

Here is the result with Cesium 3.0.6:
![CesiumBug](https://user-images.githubusercontent.com/47825483/54480807-8aa9db00-4803-11e9-83d6-c24cf5bcf6f6.gif)

**Comment by jcgter777** [comment] 2019-03-20 00:33
I always thought this was user error lol

**Comment by LogicalJoe** [comment] 2019-03-20 14:29
After doing some random tests, I now believe this is might be more of an `Input` bug since `ClrHome:Prompt A` works just fine; and `ClrHome:Wait 2:Input A`  _will_ clear the screen but the cursor never gets reset.
I haven't found any other times it fails to clear the screen (yet).

**Comment by JasonTheKitten** [comment] 2019-03-30 11:34
I've always just ran the program from normal shell when this happens, never thought to report it as a bug (: but yea, I can reproduce this.

**Comment by mateoconlechuga** [comment] 2019-05-09 03:15
I hate this bug so much because I still haven't been able to fix it.

/endrant

**Comment by mateoconlechuga** [comment] 2019-05-19 02:33
fixed with 2cf8e809b11f9fbff08120058b5d8f6e444cef83

**Closed by mateoconlechuga** 2019-05-19 02:33 UTC
Labels: bug
