### ISSUE TITLE
Invert colors shortcut does not work on Python Edition calculators

### ISSUE THREAD

**Issue by TheLastMillennial** [mateoconlechuga/cesium#176] opened 2021-04-15 03:37 UTC
The invert colors shortcut does not work on my TI-84 Plus CE Python Edition L-0520P running OS 5.6.0, pressing [on]+[sto->] does nothing. All the other shortcuts seem to work: [8],[5],[2],[stat], and [prgm] all function normally.

The invert colors shortcut works on my TI-84 Plus CE L-0315 running OS 5.6.0 and it works on my TI-84 Plus CE L-0519M running OS 5.3.0 so I assume its an issue related to Python Edition calculators. All are using Cesium 3.4.1.

**Comment by adriweb** [comment] 2021-04-15 03:57
The fact that it works on the rev M indicates that it is still OK python-hardware (minus the ARM, but still) though... 🤔

**Comment by jacobly0** [comment] 2021-04-15 12:58
This is a bug that only occurs when there is an arm chip present.  The fix is to reset bit 4 of GPIO A (spi slave select) and make sure the spi is setup for communicating with the lcd (clock phase, clock polarity, master mono mode, flash, spi frame format, chip en, tx en, clk div = 12, data width = 3).

**Comment by adriweb** [comment] 2021-04-15 13:22
nice

**Comment by retronbv** [comment] 2021-10-14 13:37
Is there any hope that this bug will be fixed?

**Comment by mateoconlechuga** [comment] 2021-10-14 13:39
I don't own a python calculator so I can't test anything. If you want to send me yours sure :P

**Comment by adriweb** [comment] 2021-10-14 14:06
Get a paypal.me URL and ask everyone for like a dollar or 2, with enough people sponsoring Cesium development it should be quick \o/

**Comment by retronbv** [comment] 2021-10-14 14:20
![image](https://user-images.githubusercontent.com/49005044/137336388-2b37b670-7630-4231-8796-0387ad2e4463.jpg)
This is the fourth time I’ve done it with no idea how :l

**Comment by Marasme** [comment] 2021-10-14 16:54
It works on ti-83 !
Thanks...

**Comment by Marasme** [comment] 2021-11-08 15:59
Hey guys !
I have a friend who have a ti-83 premium python edition but invert colors don't work. It's make a white screen !

**Comment by Marasme** [comment] 2021-11-08 16:00
And we have to use the reset button to continue tobuse the calculatrice

**Comment by TheLastMillennial** [comment] 2021-11-08 16:03
@Marasme did you try this?
> 
> 
> ...just go to the calculator's mode menu and then open Cesium.

**Comment by Marasme** [comment] 2021-11-08 16:05
?

**Comment by Marasme** [comment] 2021-11-08 16:06
I have already lunch cesium for the first time.

**Comment by Marasme** [comment] 2021-11-08 16:09
> And we have to use the reset button to continue tobuse the calculator

No ! we can use the 2nde and on button to restart the calculator !

**Comment by TheLastMillennial** [comment] 2021-11-08 16:09
Press [mode] then press [on]+[sto->] 

Please don't submit so many responses immediately after another. If you have an addition, edit the previous one. It will help keep this issue thread clean.

**Comment by Marasme** [comment] 2021-11-08 17:48
> Press [mode] then press [on]+[sto->] 
> 
> Please don't submit so many responses in a row. If you have an addition, edit the previous one. It will help keep this issue thread clean.

I will try it tomorrow (It's 6:47 PM in France).

**Comment by Marasme** [comment] 2021-11-12 14:31
It don't works...

**Comment by retronbv** [comment] 2021-11-15 22:24
I think I have figured it out…
You can use the `[on] + [sto->]` shortcut within the first second of waking the calculator.
After that it does not trigger. Easiest way to turn on the inverted colors is holding `[on] + [sto->]` to wake the calculator. LMK if you need anything!

**Comment by adriweb** [comment] 2021-11-15 23:06
Interesting, thanks for the feedback.

**Comment by ItzzCode** [comment] 2021-11-24 02:55
> I think I have figured it out… You can use the `[on] + [sto->]` shortcut within the first second of waking the calculator. After that it does not trigger. Easiest way to turn on the inverted colors is holding `[on] + [sto->]` to wake the calculator. LMK if you need anything!

I also encountered this issue, and this works perfectly.

**Comment by InvalidJake** [comment] 2021-12-05 19:24
That's what I figured out too.

**Comment by InvalidJake** [comment] 2021-12-05 19:25
I suggest when calc turns on have cesium immediately turn on dark mode then back off then it will work.

**Comment by adriweb** [comment] 2021-12-05 19:40
> I suggest when calc turns on have cesium immediately turn on dark mode then back off then it will work.

TI has removed such hooks (startup, shutoff) a long time ago, so I don't think Cesium can do anything about that.

**Comment by retronbv** [comment] 2021-12-06 12:35
> EDIT: In fact you can toggle back and forth successfully after doing this method.

That does not seem to work on my calculator (`L-0321R`)?

**Comment by InvalidJake** [comment] 2021-12-10 02:03
Interesting


________________________________

**Comment by mpi3d** [comment] 2021-12-12 17:49
Hi,

I was able to invert colors on my TI-83 Premium CE (Edition Python) using @retronbv method of pressing `on` + `sto->` within the first second of waking the calculator on OS 5.6.
But after upgrading to OS 5.7, it has stoped working. It now draws a blank screen instead.

**Comment by InvalidJake** [comment] 2021-12-12 18:35
Watch is it like in this vid https://www.youtube.com/watch?v=tvdG9P9_GqE

**Comment by mpi3d** [comment] 2021-12-12 18:38
Yeah that's it. It does a blank screen like in the video

**Comment by InvalidJake** [comment] 2021-12-12 18:45
Yea I have no idea why I have a feeling it is un inverting the colors when it's not inverted maybe an os issue.

**Comment by mpi3d** [comment] 2021-12-12 18:47
I really don't know

**Comment by mateoconlechuga** [comment] 2021-12-24 17:20
I cannot reproduce. Invert colors works fine on 0221R python edition calculators.

**Comment by mateoconlechuga** [comment] 2021-12-25 01:49
Fixed with 3a119cc

**Closed by mateoconlechuga** 2021-12-25 01:49 UTC
Labels: bug

**Comment by mpi3d** [comment] 2022-01-03 08:52
Indeed it works! It works even better. Now I even don't need to use @retronbv method, I can just press `on` + `sto->` any time and it will work.

Thanks!

**Comment by Greyhash-dev** [comment] 2022-01-20 11:00
Hello, I have a TI-84 Plus CE-T Python Edition and dark mode is not working... When I press ON + STO it just types the sto (->) icon... Any way to fix this? Thank you! (:

**Comment by Greyhash-dev** [comment] 2022-01-20 11:12
Okay, sorry, it was my fault, something went wrong when updating cesium (did not actually update), did it again, everything working now (-:
