### ISSUE TITLE
Shortcuts don't work outside of Cesium

### ISSUE THREAD

**Issue by Orangian** [mateoconlechuga/cesium#161] opened 2020-12-17 01:30 UTC
Hi. I have a calculator running OS 5.4.0 with the latest version of Cesium installed. When I attempt to use the shortcuts that are listed as working outside of Cesium, such as ON+PGRM, they don't work at all. Is there any way to diagnose and fix this issue? It'd be pretty nice to have them, however, it isn't that big of a deal.

**Comment by mateoconlechuga** [comment] 2020-12-17 04:29
Odd question, but have you enabled them in the settings menu by pressing [mode] in Cesium?

**Comment by Orangian** [comment] 2020-12-18 16:20
Yup. It's enabled.

**Comment by mateoconlechuga** [comment] 2020-12-18 16:32
Are you holding ON while pressing PRGM?

I'm sorry about these kinds of questions; because shortcuts seem to work everywhere else.

**Comment by Orangian** [comment] 2020-12-24 05:49
Yup, I hold ON while pressing PRGM. Not sure what it could be really.

**Comment by mateoconlechuga** [comment] 2021-06-19 15:13
I'm going to close this because I have no way to reproduce it unfortunately. Feel free to reopen if you find steps that I can use to make it always happen.

**Closed by mateoconlechuga** 2021-06-19 15:13 UTC
Labels: can't reproduce, need moar info
