### ISSUE TITLE
When an app is opened in cesium, it has the chance to cause weird side effects.

### ISSUE THREAD

**Issue by Potato-Man1234** [mateoconlechuga/cesium#259] opened 2023-09-26 20:20 UTC
When an app is opened in cesium it turns the screen black for a second,  the OS validates for a second and the home screen is left as a white void (and a possible RAM reset) until you go up into history.
Steps:
open cesium
go into the apps folder
open an app (like periodic)

**Comment by mateoconlechuga** [comment] 2023-09-26 20:22
I cannot reproduce.

**Comment by Potato-Man1234** [comment] 2023-09-26 20:42
https://github.com/mateoconlechuga/cesium/assets/145854899/22319bfd-85e6-4db0-af95-e1f5d8958b49

**Comment by Potato-Man1234** [comment] 2023-09-26 21:36
Did it again and it looked like #243 but in color,  scribbling into the void before resetting

**Comment by mateoconlechuga** [comment] 2023-11-13 04:25
fixed in [8372a8a](https://github.com/mateoconlechuga/cesium/commit/8372a8ac9a80b9cb2c85c039f9993b4123808804)

**Closed by mateoconlechuga** 2023-11-13 04:25 UTC
Labels: bug
