### ISSUE TITLE
2nd quitting clears ram

### ISSUE THREAD

**Issue by slimeenergyreal** [mateoconlechuga/cesium#95] opened 2019-05-19 11:57 UTC
With this program
"For(I,1,5):Input "F",C:End"
you can clear ram.
Steps:
1. Add that code to a basic program
2. Archive that program
3. Run from cesium
4. 2nd + Quit on the input

Inputs in loops and it being archived seem to be the problem.

**Comment by mateoconlechuga** [comment] 2019-05-19 15:04
Man all the bugs are related to this one :(

**Comment by mateoconlechuga** [comment] 2019-05-19 15:19
I can't reproduce this.

**Comment by mateoconlechuga** [comment] 2019-05-19 15:22
Oh nope I got it hm.

**Comment by mateoconlechuga** [comment] 2019-05-19 22:53
Fixed with 972bdd7e2442ddcf0b10547fa60fb3e525959360 hopefully

**Closed by mateoconlechuga** 2019-05-19 22:53 UTC
Labels: bug
