### ISSUE TITLE
Weird screen bug after installing cesium

### ISSUE THREAD

**Issue by BenBenny11** [mateoconlechuga/cesium#216] opened 2022-06-16 06:39 UTC
After I installed Cesium, I opened the application, then quit it, then the calculator screen itself had some weird bug after
![issue](https://user-images.githubusercontent.com/50433844/174007631-498e843d-8036-46a0-b144-1b94ec110104.png)
.

**Comment by BenBenny11** [comment] 2022-06-16 06:40
You might need to zoom in on the screen its a bit small

**Comment by mateoconlechuga** [comment] 2022-09-11 03:44
I cannot reproduce with latest Cesium. What version are you using?

**Comment by mateoconlechuga** [comment] 2022-09-11 03:49
Okay I can reproduce now :)

**Comment by mateoconlechuga** [comment] 2022-09-12 04:20
Probably fixed with [b7eb747](https://github.com/mateoconlechuga/cesium/commit/b7eb74789d46aec816676c66c357706d5b6f1522)

**Closed by mateoconlechuga** 2022-09-12 04:20 UTC
Labels: bug
