### ISSUE TITLE
Can bypass the password protection

### ISSUE THREAD

**Issue by CiaranGruber** [mateoconlechuga/cesium#145] opened 2020-07-20 14:06 UTC
Currently using Cesium v3.2.2 (On TI-84 Plus CE).

To bypass the password
1. Turn off calculator with password
2. Plug in calculator to computer
3. Wait a couple seconds and the password prompt will disappear

This works whether the calculator starts plugged in or not. If it is plugged in, the person merely needs to unsuccessfully do the password once and the calculator will shut off, allowing the password to be bypassed when the calculator is turned on again.

**Comment by mateoconlechuga** [comment] 2020-07-20 15:18
Duplicate of #141 and #110 and #17. The password feature is a novelty, not actually secure. Thanks for the report though!

**Closed by mateoconlechuga** 2020-07-20 15:18 UTC
