### ISSUE TITLE
cesmium opens when i enter something on calculator that would usually display an error.

### ISSUE THREAD

**Issue by Connor0517** [mateoconlechuga/cesium#177] opened 2021-04-28 15:52 UTC
example:5/0,5+.

**Comment by mateoconlechuga** [comment] 2021-04-28 21:04
Clear the memory on your calculator and reinstall the latest version of Cesium. This is caused by an outdated Cesium version. Duplicate of #144

**Closed by mateoconlechuga** 2021-04-28 21:04 UTC
